"""initial_english_schema

Revision ID: 6916811b3165
Revises: 
Create Date: 2026-03-08 22:51:03.991537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6916811b3165'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bidders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legal_form', sa.String(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bidders_name', 'bidders', ['name'], unique=False)
    op.create_table('comparison_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_ref', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('case_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_sessions_market_ref'), 'comparison_sessions', ['market_ref'], unique=False)
    op.create_table('consortiums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('jv_type', sa.Enum('SOLIDAIRE', 'CONJOINTE', 'SEPARATE', name='jvtype', native_enum=False, length=50), nullable=False),
    sa.Column('market_reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('effective_date', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'AUDITOR', name='userrole', native_enum=False, length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('evaluation_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_type', sa.Enum('SINGLE', 'CONSORTIUM', name='casetype', native_enum=False, length=50), nullable=False),
    sa.Column('bidder_id', sa.UUID(), nullable=True),
    sa.Column('consortium_id', sa.UUID(), nullable=True),
    sa.Column('policy_version_id', sa.UUID(), nullable=True),
    sa.Column('market_reference', sa.String(), nullable=True),
    sa.Column('market_object', sa.Text(), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('contract_currency', sa.String(), nullable=True),
    sa.Column('contract_duration_months', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'IN_ANALYSIS', 'SCORING', 'COMPLETED', 'ARCHIVED', name='casestatus', native_enum=False, length=50), nullable=False),
    sa.Column('recommendation', sa.Enum('ACCEPT', 'CONDITIONAL_ACCEPT', 'REJECT_RECOMMENDED', name='recommendation', native_enum=False, length=50), nullable=True),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('comparison_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT','PENDING_GATE','FINANCIAL_INPUT','NORMALIZATION_DONE','RATIOS_COMPUTED','SCORING_DONE','STRESS_DONE','EXPERT_REVIEWED','CLOSED','ARCHIVED')", name='ck_evaluation_case_status'),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consortium_id'], ['consortiums.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evaluation_cases_bidder_id', 'evaluation_cases', ['bidder_id'], unique=False)
    op.create_index('ix_evaluation_cases_status', 'evaluation_cases', ['status'], unique=False)
    op.create_index('ix_evaluation_cases_updated_at', 'evaluation_cases', ['updated_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('CASE_CREATED', 'GATE_COMPUTED', 'NORMALIZATION_SAVED', 'RATIO_COMPUTED', 'INTERPRETATION_SAVED', 'STRESS_TEST_COMPUTED', 'SCORECARD_COMPUTED', 'OVERRIDE_ADDED', 'REPORT_GENERATED', 'REPORT_EXPORTED', 'REPORT_SECTION_UPDATED', 'STATUS_CHANGED', 'POLICY_LOADED', 'SYSTEM_ERROR', 'DATA_IMPORT', name='auditeventtype', native_enum=False, length=50), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_case_id', 'audit_logs', ['case_id'], unique=False)
    op.create_index('ix_audit_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_entity_type', 'audit_logs', ['entity_type'], unique=False)
    op.create_index('ix_audit_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_table('consortium_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consortium_id', sa.UUID(), nullable=False),
    sa.Column('bidder_id', sa.UUID(), nullable=False),
    sa.Column('individual_case_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('LEADER', 'MEMBER', name='consortiumrole', native_enum=False, length=50), nullable=False),
    sa.Column('participation_pct', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('liability_type', sa.Enum('SOLIDAIRE', 'CONJOINTE', name='liabilitytype', native_enum=False, length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('participation_pct >= 0 AND participation_pct <= 100', name='ck_participation_pct'),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['consortium_id'], ['consortiums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['individual_case_id'], ['evaluation_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consortium_members_consortium_id', 'consortium_members', ['consortium_id'], unique=False)
    op.create_table('contract_capacity_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('contract_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('annual_ca_avg', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('exposition_pct', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('backlog_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('bank_guarantee', sa.Boolean(), nullable=False),
    sa.Column('bank_guarantee_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit_lines_confirmed', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_available', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('working_capital_requirement_estimate', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('advance_payment_pct', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payment_milestones_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('monthly_flows_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stress_60d_result', sa.Enum('SOLVENT', 'LIMIT', 'INSOLVENT', name='stressresult', native_enum=False, length=50), nullable=True),
    sa.Column('stress_90d_result', sa.Enum('SOLVENT', 'LIMIT', 'INSOLVENT', name='stressresult', native_enum=False, length=50), nullable=True),
    sa.Column('stress_60d_cash_position', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('stress_90d_cash_position', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('score_capacity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('capacity_conclusion', sa.Text(), nullable=True),
    sa.Column('scenarios_results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capacity_case_id', 'contract_capacity_assessments', ['case_id'], unique=False)
    op.create_table('document_evidences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('FINANCIAL_STATEMENTS', 'AUDITOR_OPINION', 'ANNEXES', 'CA_DECLARATION', 'BANK_REFERENCES', 'OTHER', name='doctype', native_enum=False, length=50), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size_kb', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'MISSING', 'INCOMPLETE', 'REJECTED', name='docstatus', native_enum=False, length=50), nullable=False),
    sa.Column('reliability_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'UNAUDITED', name='reliabilitylevel', native_enum=False, length=50), nullable=True),
    sa.Column('auditor_name', sa.String(), nullable=True),
    sa.Column('auditor_opinion', sa.Enum('UNQUALIFIED', 'QUALIFIED', 'ADVERSE', 'DISCLAIMER', name='auditoropinion', native_enum=False, length=50), nullable=True),
    sa.Column('red_flags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doc_evidence_case_id', 'document_evidences', ['case_id'], unique=False)
    op.create_index('ix_doc_evidence_doc_type', 'document_evidences', ['doc_type'], unique=False)
    op.create_index('ix_doc_evidence_fiscal_year', 'document_evidences', ['fiscal_year'], unique=False)
    op.create_table('due_diligence_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('dd_level', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Enum('OK', 'RESERVE', 'BLOCKING', name='ddverdict', native_enum=False, length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checked_by', sa.String(), nullable=True),
    sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'dd_level', name='uq_dd_case_level')
    )
    op.create_index('ix_dd_checks_case_id', 'due_diligence_checks', ['case_id'], unique=False)
    op.create_table('expert_interpretations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('liquidity_label', sa.Enum('FAIBLE', 'MODERE', 'FORT', name='interpretationlabel', native_enum=False, length=50), nullable=True),
    sa.Column('liquidity_comment', sa.Text(), nullable=True),
    sa.Column('solvency_label', sa.Enum('FAIBLE', 'MODERE', 'FORT', name='interpretationlabel', native_enum=False, length=50), nullable=True),
    sa.Column('solvency_comment', sa.Text(), nullable=True),
    sa.Column('profitability_label', sa.Enum('FAIBLE', 'MODERE', 'FORT', name='interpretationlabel', native_enum=False, length=50), nullable=True),
    sa.Column('profitability_comment', sa.Text(), nullable=True),
    sa.Column('capacity_label', sa.Enum('FAIBLE', 'MODERE', 'FORT', name='interpretationlabel', native_enum=False, length=50), nullable=True),
    sa.Column('capacity_comment', sa.Text(), nullable=True),
    sa.Column('quality_label', sa.Enum('FAIBLE', 'MODERE', 'FORT', name='interpretationlabel', native_enum=False, length=50), nullable=True),
    sa.Column('quality_comment', sa.Text(), nullable=True),
    sa.Column('dynamic_analysis_comment', sa.Text(), nullable=True),
    sa.Column('coherence_warnings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_complete', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('financial_statements_raw',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('currency_original', sa.String(), nullable=True),
    sa.Column('exchange_rate_to_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('referentiel', sa.Enum('PCG', 'CGNC', 'OHADA', 'IFRS', 'OTHER', name='referentiel', native_enum=False, length=50), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('liquid_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('inventory', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('accounts_receivable', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('other_current_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('non_current_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('intangible_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tangible_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('financial_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_liabilities_and_equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('share_capital', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reserves', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('retained_earnings_prior', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_year_earnings', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('non_current_liabilities', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('long_term_debt', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('long_term_provisions', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_liabilities', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('short_term_debt', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('accounts_payable', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_and_social_liabilities', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('other_current_liabilities', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sold_production', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('other_operating_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_of_goods_sold', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('external_expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('personnel_expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('taxes_and_duties', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('depreciation_and_amortization', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('other_operating_expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('operating_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('financial_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('financial_expenses', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('financial_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('income_before_tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('extraordinary_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('income_tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('investing_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('financing_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('change_in_cash', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('beginning_cash', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ending_cash', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('backlog_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('dividendes_distribues', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('capex', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_consolidated', sa.Integer(), nullable=True),
    sa.Column('source_notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'fiscal_year', name='uq_raw_case_year')
    )
    op.create_index('ix_fs_raw_case_id', 'financial_statements_raw', ['case_id'], unique=False)
    op.create_index('ix_fs_raw_fiscal_year', 'financial_statements_raw', ['fiscal_year'], unique=False)
    op.create_table('mcc_grade_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('policy_version_id', sa.String(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINAL', 'ARCHIVED', name='reportstatus', native_enum=False, length=50), nullable=False),
    sa.Column('recommendation', sa.Enum('ACCEPT', 'CONDITIONAL_ACCEPT', 'REJECT_RECOMMENDED', name='recommendation', native_enum=False, length=50), nullable=True),
    sa.Column('section_01_info', sa.Text(), nullable=True),
    sa.Column('section_02_objectif', sa.Text(), nullable=True),
    sa.Column('section_03_perimetre', sa.Text(), nullable=True),
    sa.Column('section_04_synthese', sa.Text(), nullable=True),
    sa.Column('section_05_profil', sa.Text(), nullable=True),
    sa.Column('section_06_analyse', sa.Text(), nullable=True),
    sa.Column('section_07_capacite', sa.Text(), nullable=True),
    sa.Column('section_08_red_flags', sa.Text(), nullable=True),
    sa.Column('section_09_attenuants', sa.Text(), nullable=True),
    sa.Column('section_10_scoring', sa.Text(), nullable=True),
    sa.Column('section_11_appreciation', sa.Text(), nullable=True),
    sa.Column('section_12_recommandation', sa.Text(), nullable=True),
    sa.Column('section_13_limites', sa.Text(), nullable=True),
    sa.Column('section_14_conclusion', sa.Text(), nullable=True),
    sa.Column('export_word_path', sa.String(), nullable=True),
    sa.Column('export_pdf_path', sa.String(), nullable=True),
    sa.Column('sections_complete_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT', 'FINAL', 'ARCHIVED')", name='ck_report_status'),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_case_id', 'mcc_grade_reports', ['case_id'], unique=False)
    op.create_index('ix_reports_created_at', 'mcc_grade_reports', ['created_at'], unique=False)
    op.create_index('ix_reports_status', 'mcc_grade_reports', ['status'], unique=False)
    op.create_table('scorecards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('policy_version_id', sa.UUID(), nullable=True),
    sa.Column('score_liquidity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('score_solvency', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('score_profitability', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('score_capacity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('score_quality', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('score_global', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('risk_class', sa.Enum('FAIBLE', 'MODERE', 'ELEVE', 'CRITIQUE', name='riskclass', native_enum=False, length=50), nullable=True),
    sa.Column('overrides_applied_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_profile', sa.String(), nullable=True),
    sa.Column('risk_description', sa.String(), nullable=True),
    sa.Column('synergy_index', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('synergy_bonus', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cross_analysis_alerts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trends_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('smart_recommendations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expert_interpretations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scorecards_case_id', 'scorecards', ['case_id'], unique=False)
    op.create_index('ix_scorecards_computed_at', 'scorecards', ['computed_at'], unique=False)
    op.create_table('financial_statements_normalized',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_statement_id', sa.UUID(), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('liquid_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('non_current_assets', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_liabilities_and_equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_liabilities', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('non_current_liabilities', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('adjustments_count', sa.Integer(), nullable=True),
    sa.Column('normalized_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_statement_id'], ['financial_statements_raw.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fs_norm_raw_id', 'financial_statements_normalized', ['raw_statement_id'], unique=False)
    op.create_table('normalization_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('raw_statement_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('adjustment_type', sa.Enum('RECLASS', 'CORRECTION', 'ESTIMATE', 'CURRENCY', 'OTHER', name='adjustmenttype', native_enum=False, length=50), nullable=False),
    sa.Column('field_affected', sa.String(), nullable=False),
    sa.Column('amount_before', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_after', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('mode', sa.Enum('add', 'replace', name='adjustmentmode', native_enum=False, length=50), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_statement_id'], ['financial_statements_raw.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_norm_adj_case_id', 'normalization_adjustments', ['case_id'], unique=False)
    op.create_index('ix_norm_adj_raw_id', 'normalization_adjustments', ['raw_statement_id'], unique=False)
    op.create_table('override_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('override_type', sa.Enum('MANUAL_UPGRADE', 'MANUAL_DOWNGRADE', 'AUTO_FLAG', name='overridetype', native_enum=False, length=50), nullable=False),
    sa.Column('red_flag_code', sa.String(), nullable=True),
    sa.Column('proposed_risk_class', sa.Enum('FAIBLE', 'MODERE', 'ELEVE', 'CRITIQUE', name='riskclass', native_enum=False, length=50), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('evidence_document_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUPERSEDED', 'CANCELLED', name='overridestatus', native_enum=False, length=50), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['document_evidences.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_override_case_id', 'override_decisions', ['case_id'], unique=False)
    op.create_index('ix_override_status', 'override_decisions', ['status'], unique=False)
    op.create_table('ratio_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('normalized_statement_id', sa.UUID(), nullable=False),
    sa.Column('current_ratio', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('quick_ratio', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_ratio', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('working_capital', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('financial_autonomy', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gearing', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest_coverage', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ebitda_margin', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('roa', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('roe', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('dso_days', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('dpo_days', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('dio_days', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_conversion_cycle', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('working_capital_requirement', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('working_capital_requirement_pct_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_flow_capacity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_flow_capacity_margin_pct', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('debt_repayment_years', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('negative_equity', sa.Integer(), nullable=True),
    sa.Column('negative_operating_cash_flow', sa.Integer(), nullable=True),
    sa.Column('z_score_altman', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('z_score_zone', sa.String(), nullable=True),
    sa.Column('coherence_alerts_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['normalized_statement_id'], ['financial_statements_normalized.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'fiscal_year', name='uq_ratio_case_year')
    )
    op.create_index('ix_ratio_sets_case_id', 'ratio_sets', ['case_id'], unique=False)
    op.create_index('ix_ratio_sets_fiscal_year', 'ratio_sets', ['fiscal_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ratio_sets_fiscal_year', table_name='ratio_sets')
    op.drop_index('ix_ratio_sets_case_id', table_name='ratio_sets')
    op.drop_table('ratio_sets')
    op.drop_index('ix_override_status', table_name='override_decisions')
    op.drop_index('ix_override_case_id', table_name='override_decisions')
    op.drop_table('override_decisions')
    op.drop_index('ix_norm_adj_raw_id', table_name='normalization_adjustments')
    op.drop_index('ix_norm_adj_case_id', table_name='normalization_adjustments')
    op.drop_table('normalization_adjustments')
    op.drop_index('ix_fs_norm_raw_id', table_name='financial_statements_normalized')
    op.drop_table('financial_statements_normalized')
    op.drop_index('ix_scorecards_computed_at', table_name='scorecards')
    op.drop_index('ix_scorecards_case_id', table_name='scorecards')
    op.drop_table('scorecards')
    op.drop_index('ix_reports_status', table_name='mcc_grade_reports')
    op.drop_index('ix_reports_created_at', table_name='mcc_grade_reports')
    op.drop_index('ix_reports_case_id', table_name='mcc_grade_reports')
    op.drop_table('mcc_grade_reports')
    op.drop_index('ix_fs_raw_fiscal_year', table_name='financial_statements_raw')
    op.drop_index('ix_fs_raw_case_id', table_name='financial_statements_raw')
    op.drop_table('financial_statements_raw')
    op.drop_table('expert_interpretations')
    op.drop_index('ix_dd_checks_case_id', table_name='due_diligence_checks')
    op.drop_table('due_diligence_checks')
    op.drop_index('ix_doc_evidence_fiscal_year', table_name='document_evidences')
    op.drop_index('ix_doc_evidence_doc_type', table_name='document_evidences')
    op.drop_index('ix_doc_evidence_case_id', table_name='document_evidences')
    op.drop_table('document_evidences')
    op.drop_index('ix_capacity_case_id', table_name='contract_capacity_assessments')
    op.drop_table('contract_capacity_assessments')
    op.drop_index('ix_consortium_members_consortium_id', table_name='consortium_members')
    op.drop_table('consortium_members')
    op.drop_index('ix_audit_event_type', table_name='audit_logs')
    op.drop_index('ix_audit_entity_type', table_name='audit_logs')
    op.drop_index('ix_audit_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_case_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_evaluation_cases_updated_at', table_name='evaluation_cases')
    op.drop_index('ix_evaluation_cases_status', table_name='evaluation_cases')
    op.drop_index('ix_evaluation_cases_bidder_id', table_name='evaluation_cases')
    op.drop_table('evaluation_cases')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('policy_versions')
    op.drop_table('consortiums')
    op.drop_index(op.f('ix_comparison_sessions_market_ref'), table_name='comparison_sessions')
    op.drop_table('comparison_sessions')
    op.drop_index('ix_bidders_name', table_name='bidders')
    op.drop_table('bidders')
    # ### end Alembic commands ###
