"""add_ia_module_tables

Revision ID: abe7f8b87247
Revises: 6916811b3165
Create Date: 2026-03-10 23:47:48.142683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abe7f8b87247'
down_revision: Union[str, Sequence[str], None] = '6916811b3165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ia_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consortium_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('consortium_id', sa.UUID(), nullable=False),
    sa.Column('jv_type', sa.String(), nullable=True),
    sa.Column('aggregation_method', sa.String(), nullable=True),
    sa.Column('weighted_score', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('synergy_index', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('synergy_bonus', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('base_risk_class', sa.String(), nullable=True),
    sa.Column('final_risk_class', sa.String(), nullable=True),
    sa.Column('weak_link_triggered', sa.Boolean(), nullable=False),
    sa.Column('weak_link_member', sa.String(), nullable=True),
    sa.Column('leader_blocking', sa.Boolean(), nullable=False),
    sa.Column('leader_override', sa.Boolean(), nullable=False),
    sa.Column('aggregated_stress', sa.String(), nullable=True),
    sa.Column('members_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mitigations_suggested_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consortium_id'], ['consortiums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index('ix_consortium_results_case_id', 'consortium_results', ['case_id'], unique=False)
    op.create_table('expert_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('analyst_id', sa.String(), nullable=False),
    sa.Column('qualitative_notes', sa.Text(), nullable=True),
    sa.Column('manual_risk_override', sa.String(), nullable=True),
    sa.Column('final_decision', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expert_reviews_case_id', 'expert_reviews', ['case_id'], unique=False)
    op.create_table('gate_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('is_gate_blocking', sa.Boolean(), nullable=False),
    sa.Column('blocking_reasons_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('reliability_level', sa.String(), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('missing_mandatory_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_optional_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reserve_flags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index('ix_gate_results_case_id', 'gate_results', ['case_id'], unique=False)
    op.create_table('ia_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ia_features_case_id'), 'ia_features', ['case_id'], unique=False)
    op.create_table('ia_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('ia_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ia_probability_default', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('ia_risk_class', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ia_predictions_case_id'), 'ia_predictions', ['case_id'], unique=False)
    op.create_table('ia_tensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('mcc_risk_class', sa.String(length=20), nullable=False),
    sa.Column('ia_risk_class', sa.String(length=20), nullable=False),
    sa.Column('tension_type', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ia_tensions_case_id'), 'ia_tensions', ['case_id'], unique=False)
    op.create_table('stress_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('scenario_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('simulated_score_global', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('simulated_risk_class', sa.String(), nullable=True),
    sa.Column('stress_results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evaluation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stress_scenario_case_id', 'stress_scenarios', ['case_id'], unique=False)
    op.add_column('financial_statements_normalized', sa.Column('fiscal_year', sa.Integer(), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('currency_usd', sa.String(), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('inventory', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('accounts_receivable', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('other_current_assets', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('intangible_assets', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('tangible_assets', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('financial_assets', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('share_capital', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('reserves', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('retained_earnings_prior', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('current_year_earnings', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('long_term_debt', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('long_term_provisions', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('short_term_debt', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('accounts_payable', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('tax_and_social_liabilities', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('other_current_liabilities', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('sold_production', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('other_operating_revenue', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('cost_of_goods_sold', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('external_expenses', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('personnel_expenses', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('taxes_and_duties', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('depreciation_and_amortization', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('other_operating_expenses', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('operating_income', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('financial_revenue', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('financial_expenses', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('financial_income', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('income_before_tax', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('extraordinary_income', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('income_tax', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('investing_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('financing_cash_flow', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('change_in_cash', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('beginning_cash', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('ending_cash', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('headcount', sa.Integer(), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('backlog_value', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('capex', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('financial_statements_normalized', sa.Column('is_consolidated', sa.Integer(), nullable=True))
    op.add_column('financial_statements_raw', sa.Column('dividends_distributed', sa.Numeric(precision=18, scale=2), nullable=True))
    op.drop_column('financial_statements_raw', 'dividendes_distribues')
    op.add_column('mcc_grade_reports', sa.Column('section_02_objective', sa.Text(), nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_03_scope', sa.Text(), nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_04_executive_summary', sa.Text(), nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_05_profile', sa.Text(), nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_06_analysis', sa.Text(), nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_07_capacity', sa.Text(), nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_09_mitigants', sa.Text(), nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_11_assessment', sa.Text(), nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_12_recommendation', sa.Text(), nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_13_limitations', sa.Text(), nullable=True))
    op.alter_column('mcc_grade_reports', 'policy_version_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='policy_version_id::uuid')
    op.create_foreign_key(None, 'mcc_grade_reports', 'policy_versions', ['policy_version_id'], ['id'], ondelete='SET NULL')
    op.drop_column('mcc_grade_reports', 'section_04_synthese')
    op.drop_column('mcc_grade_reports', 'section_07_capacite')
    op.drop_column('mcc_grade_reports', 'section_11_appreciation')
    op.drop_column('mcc_grade_reports', 'section_12_recommandation')
    op.drop_column('mcc_grade_reports', 'section_13_limites')
    op.drop_column('mcc_grade_reports', 'section_05_profil')
    op.drop_column('mcc_grade_reports', 'section_06_analyse')
    op.drop_column('mcc_grade_reports', 'section_02_objectif')
    op.drop_column('mcc_grade_reports', 'section_09_attenuants')
    op.drop_column('mcc_grade_reports', 'section_03_perimetre')
    op.create_unique_constraint('uq_scorecard_case_time', 'scorecards', ['case_id', 'computed_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_scorecard_case_time', 'scorecards', type_='unique')
    op.add_column('mcc_grade_reports', sa.Column('section_03_perimetre', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_09_attenuants', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_02_objectif', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_06_analyse', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_05_profil', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_13_limites', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_12_recommandation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_11_appreciation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_07_capacite', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mcc_grade_reports', sa.Column('section_04_synthese', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mcc_grade_reports', type_='foreignkey')
    op.alter_column('mcc_grade_reports', 'policy_version_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='policy_version_id::varchar')
    op.drop_column('mcc_grade_reports', 'section_13_limitations')
    op.drop_column('mcc_grade_reports', 'section_12_recommendation')
    op.drop_column('mcc_grade_reports', 'section_11_assessment')
    op.drop_column('mcc_grade_reports', 'section_09_mitigants')
    op.drop_column('mcc_grade_reports', 'section_07_capacity')
    op.drop_column('mcc_grade_reports', 'section_06_analysis')
    op.drop_column('mcc_grade_reports', 'section_05_profile')
    op.drop_column('mcc_grade_reports', 'section_04_executive_summary')
    op.drop_column('mcc_grade_reports', 'section_03_scope')
    op.drop_column('mcc_grade_reports', 'section_02_objective')
    op.add_column('financial_statements_raw', sa.Column('dividendes_distribues', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
    op.drop_column('financial_statements_raw', 'dividends_distributed')
    op.drop_column('financial_statements_normalized', 'is_consolidated')
    op.drop_column('financial_statements_normalized', 'capex')
    op.drop_column('financial_statements_normalized', 'backlog_value')
    op.drop_column('financial_statements_normalized', 'headcount')
    op.drop_column('financial_statements_normalized', 'ending_cash')
    op.drop_column('financial_statements_normalized', 'beginning_cash')
    op.drop_column('financial_statements_normalized', 'change_in_cash')
    op.drop_column('financial_statements_normalized', 'financing_cash_flow')
    op.drop_column('financial_statements_normalized', 'investing_cash_flow')
    op.drop_column('financial_statements_normalized', 'income_tax')
    op.drop_column('financial_statements_normalized', 'extraordinary_income')
    op.drop_column('financial_statements_normalized', 'income_before_tax')
    op.drop_column('financial_statements_normalized', 'financial_income')
    op.drop_column('financial_statements_normalized', 'financial_expenses')
    op.drop_column('financial_statements_normalized', 'financial_revenue')
    op.drop_column('financial_statements_normalized', 'operating_income')
    op.drop_column('financial_statements_normalized', 'other_operating_expenses')
    op.drop_column('financial_statements_normalized', 'depreciation_and_amortization')
    op.drop_column('financial_statements_normalized', 'taxes_and_duties')
    op.drop_column('financial_statements_normalized', 'personnel_expenses')
    op.drop_column('financial_statements_normalized', 'external_expenses')
    op.drop_column('financial_statements_normalized', 'cost_of_goods_sold')
    op.drop_column('financial_statements_normalized', 'other_operating_revenue')
    op.drop_column('financial_statements_normalized', 'sold_production')
    op.drop_column('financial_statements_normalized', 'other_current_liabilities')
    op.drop_column('financial_statements_normalized', 'tax_and_social_liabilities')
    op.drop_column('financial_statements_normalized', 'accounts_payable')
    op.drop_column('financial_statements_normalized', 'short_term_debt')
    op.drop_column('financial_statements_normalized', 'long_term_provisions')
    op.drop_column('financial_statements_normalized', 'long_term_debt')
    op.drop_column('financial_statements_normalized', 'current_year_earnings')
    op.drop_column('financial_statements_normalized', 'retained_earnings_prior')
    op.drop_column('financial_statements_normalized', 'reserves')
    op.drop_column('financial_statements_normalized', 'share_capital')
    op.drop_column('financial_statements_normalized', 'financial_assets')
    op.drop_column('financial_statements_normalized', 'tangible_assets')
    op.drop_column('financial_statements_normalized', 'intangible_assets')
    op.drop_column('financial_statements_normalized', 'other_current_assets')
    op.drop_column('financial_statements_normalized', 'accounts_receivable')
    op.drop_column('financial_statements_normalized', 'inventory')
    op.drop_column('financial_statements_normalized', 'exchange_rate')
    op.drop_column('financial_statements_normalized', 'currency_usd')
    op.drop_column('financial_statements_normalized', 'fiscal_year')
    op.drop_index('ix_stress_scenario_case_id', table_name='stress_scenarios')
    op.drop_table('stress_scenarios')
    op.drop_index(op.f('ix_ia_tensions_case_id'), table_name='ia_tensions')
    op.drop_table('ia_tensions')
    op.drop_index(op.f('ix_ia_predictions_case_id'), table_name='ia_predictions')
    op.drop_table('ia_predictions')
    op.drop_index(op.f('ix_ia_features_case_id'), table_name='ia_features')
    op.drop_table('ia_features')
    op.drop_index('ix_gate_results_case_id', table_name='gate_results')
    op.drop_table('gate_results')
    op.drop_index('ix_expert_reviews_case_id', table_name='expert_reviews')
    op.drop_table('expert_reviews')
    op.drop_index('ix_consortium_results_case_id', table_name='consortium_results')
    op.drop_table('consortium_results')
    op.drop_table('ia_models')
    # ### end Alembic commands ###
